package generator;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName sys_role
 */
@Data
public class SysRole implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sat Dec 26 23:10:17 CST 2020
     */
    private Long roleId;

    /**
     * 角色名称
     *
     * @mbg.generated Sat Dec 26 23:10:17 CST 2020
     */
    private String roleName;

    /**
     * 备注
     *
     * @mbg.generated Sat Dec 26 23:10:17 CST 2020
     */
    private String remark;

    /**
     * 创建者ID
     *
     * @mbg.generated Sat Dec 26 23:10:17 CST 2020
     */
    private Long createUserId;

    /**
     * 创建时间
     *
     * @mbg.generated Sat Dec 26 23:10:17 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_role
     *
     * @mbg.generated Sat Dec 26 23:10:17 CST 2020
     */
    private static final long serialVersionUID = 1L;
}