package generator;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName tb_user
 */
@Data
public class TbUser implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sat Dec 26 19:42:54 CST 2020
     */
    private Long userId;

    /**
     * 用户名
     *
     * @mbg.generated Sat Dec 26 19:42:54 CST 2020
     */
    private String username;

    /**
     * 手机号
     *
     * @mbg.generated Sat Dec 26 19:42:54 CST 2020
     */
    private String mobile;

    /**
     * 密码
     *
     * @mbg.generated Sat Dec 26 19:42:54 CST 2020
     */
    private String password;

    /**
     * 创建时间
     *
     * @mbg.generated Sat Dec 26 19:42:54 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbg.generated Sat Dec 26 19:42:54 CST 2020
     */
    private static final long serialVersionUID = 1L;
}