# Tomcat
server:
    port: 8080

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
      default-property-inclusion: non_null
  # redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大空闲
          max-idle: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1ms
          #最小空闲
          min-idle: 0
      #连接超时时间
      timeout: 1000ms
    servlet:
      multipart:
        maxFileSize: 104857600 #100MB
        maxRequestSize: 104857600 #100MB
    application:
      name: 皮卡丘

# 暴露监控端点后会打印所有的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Repository.xml
  typeEnumsPackage: com.panji.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true




